version: "3"
#services:
# db:
#   image: mongodb
#   restart: always
#   environment:
#     MONGODB_DATABASE: "weather-on-mars"
#     MONGODB_USER: "earth"
#     MONGODB_PASSWORD: "earth"
#     MONGODB_ENCODING: "UNICODE"
#   ports:
#     - "48000:5432"

